# TODO -- replace with community.general.pacman module?
- name: init pacman keychain
  shell:
    cmd: 'pacman-key --init'

- name: populate archlinuxarm keys
  shell:
    cmd: 'pacman-key --populate archlinuxarm'

- name: update everything
  shell:
    cmd: 'pacman -Syu --noconfirm'

- name: install required packages
  shell:
    cmd: 'pacman -S --noconfirm python python-pip ufw gcc sudo vim'

- name: ensure root user is locked
  become: yes
  user:
    name: "root"
    password_lock: yes

- name: ensure SSH password auth is disabled
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"

- name: ensure SSH challenge response auth is disabled
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication no"

- name: ensure SSH login is limited to home network
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AllowUsers"
    line: "AllowUsers root@{{ admin_subnet_ssh }} {{ admin_user }}@{{ admin_subnet_ssh }}"

- name: ensure ufw allows traffic on port 22 from home network
  ufw:
    comment: "ssh from home network"
    rule: allow
    from_ip: "{{ admin_subnet }}"
    to_port: "22"

- name: apply SSH config updates
  service:
    name: sshd
    state: restarted

- name: ensure ufw blocks all other incoming connections by default
  ufw:
    default: deny
    direction: incoming

- name: ensure ufw is enabled
  ufw:
    state: enabled

- name: ensure ufw systemd service is enabled
  service:
    name: ufw
    enabled: yes
    state: started

- name: ensure glances is installed
  pip:
    name: glances
    executable: pip3
